# Pandas DataFrame


In [1]:
import pandas as pd

In [2]:
# creating a DataFrame
df=pd.DataFrame([11,22,33,44,55])
df

0
0  11
1  22
2  33
3  44
4  55

In [3]:
# create a Data Frame from Nested List
df=pd.DataFrame([['Priyang',98],['Vedant',89],['Parsh',88]])
df

0   1
0  Priyang  98
1   Vedant  89
2    Parsh  88

In [4]:
# Create a Data Frame from Dictionary  
df=pd.DataFrame({'Name':['Priyang','Aadhya','Krishna'],'Marks':[98,89,99]})
df


Name  Marks
0  Priyang     98
1   Aadhya     89
2  Krishna     99

In [5]:
# create a Data Frame from Numpy

import numpy as np
data=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
df=pd.DataFrame(data, columns=['a','b','c'],index=[1,2,3])
df

a  b  c
1  1  2  3
2  4  5  6
3  7  8  9

In [6]:
# create a DataFrame using series
d={'First':pd.Series(['a','b','c','d']),
   'Second':pd.Series(['x','y','z','w'])}
df=pd.DataFrame(d)
df

First Second
0     a      x
1     b      y
2     c      z
3     d      w

In [7]:
# Create a Data Frame from Dictionary (with Index)
dict1={'Name':['Priyang','Aadhya','Krisha'],
       'Marks':[98,89,99]}
df=pd.DataFrame(dict1, index=['stu1','stu2','stu3'])
df

Name  Marks
stu1  Priyang     98
stu2   Aadhya     89
stu3   Krisha     99

In [8]:

# Create a Data Frame from Dictionary ( with Columns)
list1=[['Priyang',98],['Vedant',89],['Parshv',99]]
df=pd.DataFrame(list1, columns=['Name','Marks'])
df

Name  Marks
0  Priyang     98
1   Vedant     89
2   Parshv     99

In [9]:
# Create a DataFrame from Dictionary ( with Dtype)
dict1={'Name':['Priyang','Aadhya','Krisha'],
       'Marks':[98,89,99]}
df=pd.DataFrame(dict1, columns=['Name','Marks'],
                index=['stu1','stu2','stu3'],dtype='float')
df

Name  Marks
stu1  Priyang   98.0
stu2   Aadhya   89.0
stu3   Krisha   99.0

# loc vs iloc


In [10]:
import pandas as pd
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
        'Mittal','Archana'],
        'Marks':[98,89,99,87,90,83,82],
        'Grades':['AA','AB','AA','AB','AC','BA','BB']
        }
df1=pd.DataFrame(dict1)


In [11]:
df1

Name  Marks Grades
0  Priyang     98     AA
1   Aadhya     89     AB
2   Krisha     99     AA
3   Vedant     87     AB
4   Parshv     90     AC
5   Mittal     83     BA
6  Archana     82     BB

In [12]:
# first row with all the columns
df1.loc[0,:]

Name      Priyang
Marks          98
Grades         AA
Name: 0, dtype: object

In [13]:
# select row [0,1,2] with all the columns
df1.loc[[0,1,2],:]

Name  Marks Grades
0  Priyang     98     AA
1   Aadhya     89     AB
2   Krisha     99     AA

In [14]:
# even we can do slicing operation
df1.loc[0:2,:]

Name  Marks Grades
0  Priyang     98     AA
1   Aadhya     89     AB
2   Krisha     99     AA

In [15]:
df1

Name  Marks Grades
0  Priyang     98     AA
1   Aadhya     89     AB
2   Krisha     99     AA
3   Vedant     87     AB
4   Parshv     90     AC
5   Mittal     83     BA
6  Archana     82     BB

In [16]:
# all the rows with Name column only
df1.loc[:,'Name']

0    Priyang
1     Aadhya
2     Krisha
3     Vedant
4     Parshv
5     Mittal
6    Archana
Name: Name, dtype: object

In [17]:
# all the rows with multiple columns like 'Name','Marks'
df1.loc[:,['Name','Marks']]

Name  Marks
0  Priyang     98
1   Aadhya     89
2   Krisha     99
3   Vedant     87
4   Parshv     90
5   Mittal     83
6  Archana     82

In [18]:
# all the rows start with Name columns to remaining all columns
df1.loc[:,'Name':]

Name  Marks Grades
0  Priyang     98     AA
1   Aadhya     89     AB
2   Krisha     99     AA
3   Vedant     87     AB
4   Parshv     90     AC
5   Mittal     83     BA
6  Archana     82     BB

In [19]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
        'Mittal','Archana'],
        'Marks':[98,89,99,87,90,83,82],
        'Grades':['AA','AB','AA','AB','AC','BA','BB']
        }
df1=pd.DataFrame(dict1,index=['stu1','stu2','stu3','stu4','stu5','stu6','stu7'])

In [20]:
df1

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB
stu3   Krisha     99     AA
stu4   Vedant     87     AB
stu5   Parshv     90     AC
stu6   Mittal     83     BA
stu7  Archana     82     BB

## iloc : access the group of rows and columns by integer position or positions

In [21]:
# i want to print all the rows of first column
df1.iloc[:,0]

stu1    Priyang
stu2     Aadhya
stu3     Krisha
stu4     Vedant
stu5     Parshv
stu6     Mittal
stu7    Archana
Name: Name, dtype: object

In [22]:
# all the rows with multiple columns
df1.iloc[:,0:2]

Name  Marks
stu1  Priyang     98
stu2   Aadhya     89
stu3   Krisha     99
stu4   Vedant     87
stu5   Parshv     90
stu6   Mittal     83
stu7  Archana     82

In [23]:
# i want to access Name, Marks and Grades of stu1 & stu2
df1.loc[['stu1','stu2'],:]

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB

In [24]:
# Name of stu1 and stu4
df1.loc['stu1':'stu4','Name']

stu1    Priyang
stu2     Aadhya
stu3     Krisha
stu4     Vedant
Name: Name, dtype: object

In [25]:
# now using iloc --> name,marks of stu1,stu2
df1.iloc[[0,1],[0,1]]

Name  Marks
stu1  Priyang     98
stu2   Aadhya     89

In [26]:
# using iloc --> all the columns with stu1,stu2
df1.iloc[0:2,:]

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB

### loc : Access A Group Of Rows And Columns By Label(s)

In [27]:
df1

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB
stu3   Krisha     99     AA
stu4   Vedant     87     AB
stu5   Parshv     90     AC
stu6   Mittal     83     BA
stu7  Archana     82     BB

## 1.Name, Marks and Grades of stu1 and stu2

In [28]:
df1.loc[['stu1','stu2'],:]

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB

## 2. Name and Grades of stu1, stu3 and stu5

In [29]:
df1.loc[['stu1','stu3','stu5'],['Name','Grades']]

Name Grades
stu1  Priyang     AA
stu3   Krisha     AA
stu5   Parshv     AC

## 3. Name,Marks and Grades of stu1 and stu7

In [30]:
df1.loc['stu1':'stu7',:]

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB
stu3   Krisha     99     AA
stu4   Vedant     87     AB
stu5   Parshv     90     AC
stu6   Mittal     83     BA
stu7  Archana     82     BB

## iloc: Access A Group Of Rows And Columns By Integer Position(s)

## 4. Name,Marks and Grades of stu1 and stu2

In [31]:
df1.iloc[[0,1],:]

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB

## 5. Name and Marks of stu1,stu3, and stu5

In [32]:
df1.iloc[[0,2,4],[0,1]]

Name  Marks
stu1  Priyang     98
stu3   Krisha     99
stu5   Parshv     90

## 6.Name,Marks and Grades of stu1 to stu7

In [33]:
df1.iloc[0:7,:]

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB
stu3   Krisha     99     AA
stu4   Vedant     87     AB
stu5   Parshv     90     AC
stu6   Mittal     83     BA
stu7  Archana     82     BB

### iat: Access a single value for a row/column pair by integer position,Similar to iloc ,
### in that both provide integer-based lookups.Use iat if you only need to get or set a single value

### 7.print Grade of stu2

In [34]:
df1.iat[1,2]

'AB'

### 8. Print Name of stu5

In [35]:
df1.iat[4,0]

'Parshv'

### 9. Set Marks of stu5 to 99

In [36]:
df1

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB
stu3   Krisha     99     AA
stu4   Vedant     87     AB
stu5   Parshv     90     AC
stu6   Mittal     83     BA
stu7  Archana     82     BB

In [37]:

df1.iat[4,1]=99

In [38]:
df1

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB
stu3   Krisha     99     AA
stu4   Vedant     87     AB
stu5   Parshv     99     AC
stu6   Mittal     83     BA
stu7  Archana     82     BB

### 10. print Grade of stu2 using 'at' keyword

In [39]:
df1.at['stu2','Grades']

'AB'

### 11. print name of stud5

In [40]:
df1.at['stu5','Name']

'Parshv'

### 12. set Marks of stu5 to 99

In [41]:
df1.at['stu5','Marks']=100

In [42]:
df1

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB
stu3   Krisha     99     AA
stu4   Vedant     87     AB
stu5   Parshv    100     AC
stu6   Mittal     83     BA
stu7  Archana     82     BB

### loc & iloc with Boolean Array

In [43]:
df1

Name  Marks Grades
stu1  Priyang     98     AA
stu2   Aadhya     89     AB
stu3   Krisha     99     AA
stu4   Vedant     87     AB
stu5   Parshv    100     AC
stu6   Mittal     83     BA
stu7  Archana     82     BB

In [44]:
# Boolean Array size must be the same as your Dataframe size.
# Boolean list with the same length as the row axis & column axis
# df1.[(rows(s),column(s))]


df1.loc[[False,False,False,False,False,False,False],[False,False,False]]

Empty DataFrame
Columns: []
Index: []

### 1.Name of Stu1 and Stu2

In [45]:
df1.loc[[True,True,False,False,False,False,False],[True,False,False]]

Name
stu1  Priyang
stu2   Aadhya

### 2.Grades of stu1 and stu5

In [46]:
df1.loc[[True,False,False,False,True,False,False],[False,False,True]]

Grades
stu1     AA
stu5     AC

### 3.Mark of stu4

In [47]:
df1.loc[[False,False,False,True,False,False,False],[False,True,False]]

Marks
stu4     87

In [48]:
# using iloc also same process above 3 steps

df1.iloc[[False,False,False,True,False,False,False],[False,True,False]]

Marks
stu4     87

# Converts DataFrame values to Numpy Array

In [49]:
data=pd.read_csv('iris.csv')
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [59]:
data.shape

(150, 5)

In [50]:
pd.read_csv()

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'

In [51]:
type(data)

pandas.core.frame.DataFrame

In [52]:
data_numpy=data.values

In [53]:
data_numpy

array([[5.1, 3.5, 1.4, 0.2, 'Setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Setosa'],
       [5.1, 3.3, 1.7, 0.5, 'Setosa'],
       [4.8, 3.4, 1.9, 0.2, 'Setosa'],
       [5.0, 3.0, 1.6, 0.

In [54]:
data.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [56]:
data1=data['sepal.length'].values
data1

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [57]:
type(data1)

numpy.ndarray

In [58]:
data.to_numpy()

array([[5.1, 3.5, 1.4, 0.2, 'Setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Setosa'],
       [5.1, 3.3, 1.7, 0.5, 'Setosa'],
       [4.8, 3.4, 1.9, 0.2, 'Setosa'],
       [5.0, 3.0, 1.6, 0.