### 0 - D Array    a single data point
### 1 - D Array    a sequence of values
### 2 - D Array    a collection of 1 - D Sequences

**installation**

pip install numpy


**upgrade for latest version**

pip install numpy --upgrade

### Checking NumPy Version
The version string is stored under __version__ attribute.

In [5]:
print(np.__version__)


1.19.5


## Importing *Numpy*

In [2]:
import numpy as np

## Creating a ndarray object

In [3]:
 a = np.array 

In [4]:
print (a)

<built-in function array>


## Create a NumPy ndarray Object

In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [7]:
arr

array([1, 2, 3, 4, 5])

## type(): This built-in Python function tells us the type of the object passed to it

In [8]:
type(arr)

numpy.ndarray

In [9]:
print(type(arr))

<class 'numpy.ndarray'>


### Use a tuple to create a NumPy array:

In [10]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [11]:
type(arr)

numpy.ndarray

# **Dimensions in Arrays**
### A dimension in arrays is one level of array depth (nested arrays).


## **0-D Arrays**

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.



In [13]:
# Create a 0-D array with value 42


arr = np.array(42)

print(arr)

42


# **1-D Arrays**

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [14]:
# Create a 1-D array containing the values 1,2,3,4,5:


arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# ***2-D Arrays***

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [15]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# **3-D arrays**

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [20]:
# create a 3-D Array

arr = np.array([[[1, 2, 3], [4, 5, 6], [1, 2, 3]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [1 2 3]]]


In [16]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# **Check Number of Dimensions?**

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.



In [22]:
# Check how many dimensions the arrays have:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# **Higher Dimensional Arrays**

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [24]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


#**Numpy size() function**

In [25]:
# Making a random array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
# By default, give the total number of elements.
print(np.size(arr))

8


In [26]:
# Making a random array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
# count the number of elements along the axis.
# Here rows and columns are being treated
# as elements
 
#gives no. of rows along x-axis
print(np.size(arr, 0))
 
#gives no. of columns along y-axis
print(np.size(arr, 1))

2
4


# Get the Shape of an Array

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [16]:
# Print the shape of a 2-D array:

arr = np.array([[[[[1, 2, 3, 4],[5, 6, 7, 8]]]]])

print(arr.shape)

(1, 1, 1, 2, 4)


In [9]:
# Create an array with 1 dimensions using ndmin using a vector with values 1,2,3,4:


arr = np.array([1, 2, 3, 4], ndmin=2)

print(arr)
print('shape of array :', arr.shape)

[[1 2 3 4]]
shape of array : (1, 4)
